### ISSUE TITLE
Question about mime

### ISSUE THREAD

**Issue by MarcHagen** [abdus/nginx-pretty-index#2]
Just a question, as you seem to know this stuff better than i do.
I've found this mirror site which has the MIME type of a File listed.
https://mirror.operationtulip.com/AST/

Is this also possible to apply on your pretty index?

**Comment by abdus** [comment]
You can always use JavaScript to parse the filename, and show Mime icon based on the file extension. Here's the `img` tag you will have to modify:

https://github.com/abdus/nginx-pretty-index/blob/main/styles.xslt#L108,L110

**Comment by MarcHagen** [comment]
Ah yes, good old javascript. Thank you for getting back to me :)
