### ISSUE TITLE
This XML file does not appear to have any style information associated with it. The document tree is shown below. <list> </list>

### ISSUE THREAD

**Issue by stefanpejcic** [abdus/nginx-pretty-index#3]
After adding:

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<list> </list>

`root@stefan9:/# nginx -v
nginx version: nginx/1.18.0 (Ubuntu)
`

**Comment by abdus** [comment]
@stefanpejcic you will have to install the [xslt module](https://nginx.org/en/docs/http/ngx_http_xslt_module.html), and load it via Nginx Config.
